--Region of Attica
insert into monument (name,place,region,description,point) values('PARTHENON','ATHENS','ATTICA','The magnificent temple on the Acropolis of Athens, known as the Parthenon, was built between 447 and 432 BCE in the Age of Pericles, and it was dedicated to the city’s patron deity Athena.The temple was constructed to house the new cult statue of the goddess by Pheidias and to proclaim to the world the success of Athens as leader of the coalition of Greek forces which had defeated the invading Persian armies of Darius and Xerxes.The temple would remain in use for more than a thousand years, and despite the ravages of time, explosions, looting, and pollution damage, it still dominates the modern city of Athens, a magnificent testimony to the glory and renown the city enjoyed throughout antiquity.',st_GeomFromText('POINT(37.9715285 23.7267166)',132));
insert into monument (name,place,region,description,point) values('ANCIENT EPIDAURUS','ATHENS','ATTICA','Probably the most beautiful and best preserved of its kind, the theater of Epidaurus was built in the 4th century BC by Polykleitos the Younger. Due to its excellent acoustics and condition, the ancient theater is still used today, most notably under the framework of the annual Epidaurus Festival',st_GeomFromText('POINT(37.596078 23.079244)',132));

--Region of Central Macedonia
insert into monument (name,place,region,description,point) values('APOSTLE PAULS ALTAR','VERIA','CENTRAL MACEDONIA','After being chased from Thessaloniki the Apostle Paul went to Veria, where he preached the Holy Gospel to jews and Greeks.The spot in Veria where Paul stood and preached, is called the "Apostle Pauls Altar and is now an imposing monument with beautiful mosaics',st_GeomFromText('POINT(40.519362 22.205216)',132));
insert into monument (name,place,region,description,point) values('MUSEUM OF ROYAL TOMBS OF AIGAI','VERGINA','CENTRAL MACEDONIA','The museum has a dark,imposing atmosphere that surprises most visitors.Some of the most impressive and important exhibits from the Macedonian dominated period of the Greek history are available in the exact location that the original excavations took place. The museum was built in 1993, 16 years after the discovery of the Royal tombs in Aiges.It was built in order to create ideal conditions considering the humidity and temperature needed for the findings to be properly preserved and protected. Inside the museum there are four separate tombs and the “Heroon”, a small temple built for Phillip II of Macedon.',st_GeomFromText('POINT(40.487537 22.320730)',132));
insert into monument (name,place,region,description,point) values('ROTONDA','THESSALONIKI','CENTRAL MACEDONIA','The famous Rotonda of Thessaloniki, Macedonia: The Rotonda (or Rotunda) is one of the most important Roman monuments in Thessaloniki. It stands just next to the Arch of Galerius in the city center and it is also known as the Church of Agios Georgios. This cylindrical structure was built in 306 AD by the Roman tetrarch Galerius, who intended it to be his grave. At first, it worked as a temple but it remains unknown to which god this temple was dedicated.',st_GeomFromText('POINT(40.633301 22.952854)',132));
insert into monument (name,place,region,description,point) values('THE GALERIUS PALACE','THESSALONIKI','CENTRAL MACEDONIA','Where Navarinou Square and Demetriou Gounari Street is now located, a significant part of the Galerius Palace complex has been excavated including massive walls, a large internal courtyard, peristyle, corridors and rooms with beautiful mosaic floors, fountains and springs. On the southwest part of the site is where the Octagon lies, a large octagonal stucture of almost 30m in internal diameter, which was a temple or the throne room with a wonderful floor paving remaining. The Hippodrome (400m in length), lies on the east of the Palace, unfortunately underneath the block of flats in the Hippodrome Square. Many of its remaining marbles and stones were later used in various repairs to the western walls.',st_GeomFromText('POINT(40.630353 22.948980)',132));
insert into monument (name,place,region,description,point) values('THE ROMAN MARKET','THESSALONIKI','CENTRAL MACEDONIA','During the Roman period, this marketplace represented the social and religious center of the town and had the most imposing buildings. The complex of the Roman market was constructed around a rectangular square. In the three sides, there were two lofts. The southern loft was seating at a double vaulting which was a semi-basement on the one side.On the eastern loft of the transept, there was a building display. According to a sign, it functioned as a conservatory. During the Byzantine Period, the buildings were deserted and destroyed by earthquakes or enemy invasions.',st_GeomFromText('POINT(40.630353 22.948980)',132));
insert into monument (name,place,region,description,point) values('MILITARY GRAVES','KILKIS','CENTRAL MACEDONIA','In the settlement of Kristoni, 5 km. south of Kilkis, the Sargkiol Graves are located; the British military graves of the fallen during the First World War.',st_GeomFromText('POINT(40.952375 22.855354)',132));
insert into monument (name,place,region,description,point) values('WAR MUSEUM OF KILKIS','KILKIS','CENTRAL MACEDONIA','This impressive monument is located south of the city of Kilkis, in a stunning natural environment, and it is dedicated to the fallen of the murderous and decisive Battle of Kilkis. This battle took place on 21st June 1913, while on the same location the War Museum of Kilkis operates since 1966, exhibiting rare artifacts from the Balkan wars.',st_GeomFromText('POINT(40.977842 22.852140)',132));
insert into monument (name,place,region,description,point) values('SCHOOL OF ARISTOTLE','NAOUSA','CENTRAL MACEDONIA','A place of universal interest, the ruins of Aristotles School, is a found only 2 kilometers away from the contemporary Naoussa, at the district of Isvoria Here is the place with the racing water and the deeply-shaded caves, mentioned by the ancient writers, where the greatest philosopher of the antiquity taught the greatness of classical Greek thought and the ideals of the Platonic philosophy to the Kings of Macedonia, Phillip II, son, Alexander and the other nobles of the Macedonian court. The encounter of these two Great personalities of the ancient world at the Nympheon of Mieza would definitely affect the future of mankind, and of all Western Civilization.',st_GeomFromText('POINT(40.629811 22.100269)',132));
insert into monument (name,place,region,description,point) values('PLACE OF SACRIFICE','NAOUSA','CENTRAL MACEDONIA','Sacrifice site in Naoussa, Imathia. Here, on April 22, 1822, "the women and children of Naoussa died gloriously and tragically for the freedom and independence of the Greek nation."',st_GeomFromText('POINT(40.626796 22.064542)',132));
insert into monument (name,place,region,description,point) values('PLATAMON CASTLE','PLATAMONAS','CENTRAL MACEDONIA','The Platamon Castle is a castle of the middle Byzantine period (10th century AD) and is located southeast of Mount Olympus.The castle is located in a strategic positon, at the exit of the Tempi valey and it controls the route from Macedonia to Thessaly and to Southern Greece',st_GeomFromText('POINT(40.005145 22.598205)',132));
insert into monument (name,place,region,description,point) values('DION ARCHAEOLOGICAL PARK','DION','CENTRAL MACEDONIA','The Archaeological Park of Dion is the most important archaeological site at Mount Olympus in Greece, located in Dion.In the area comprised by the Archaeological Park of Dion, sanctuaries were found from the Hellenistic and Roman periods.The park displays the importance of ancient Dion in the history of Pieria.',st_GeomFromText('POINT(40.175761 22.491374)',132));
insert into monument (name,place,region,description,point) values('FORT ROUPEL','SERRES','CENTRAL MACEDONIA','Fort Roupel is a fortress at the north border of Central Macedonia, Greece, built in 1914. It became part of the fortifications of the Metaxas Line in the 1930s and became famous for its defence during the German invasion of Greece in April 1941',st_GeomFromText('POINT(41.345850 23.370298)',132));
insert into monument (name,place,region,description,point) values('ANCIENT STAGIRA','STAGIRA','CENTRAL MACEDONIA','The most important historical area of Halkidiki,the ancient Stageira,are located in the area of Liotopi,just next to today’s Olimpiada.The city was founded in 655 BC by Ionian settlers from the island of Andros,while a little later settlers from Chalkida arrived.After the Persian wars Stageira were also made part of the Athenian Alliance, contributing to the common fund. During the Peloponnesian war but specifically in 424 BC, the city defected from the Athenians and allied with the Spartans. That angered the Athenians, who hastened to besiege the city, but without a result.',st_GeomFromText('POINT(40.591705 23.796035)',132));
insert into monument (name,place,region,description,point) values('POSEIDONS TEMPLE','CHALKIDIKI','CENTRAL MACEDONIA','On the flat surface of Cape Posidi, 4 km west of the city, the excavation brought to light the sanctuary of Mendes, which was dedicated to Neptune. As the geological survey found, the sanctuary occupies the entire area of ​​a sandy peninsula, about 150 meters wide and 60 in width, so that its buildings are projected into the sea, like the corresponding temples in Sounio and Naxos.',st_GeomFromText('POINT(39.958930 23.363706)',132));
insert into monument (name,place,region,description,point) values('NEPOSIS CASTLE','CHALKIDIKI','CENTRAL MACEDONIA','The biggest fortress in Chalkidiki. It was built in the 5th century AD at a location inhabited since the 15th century BC.At some time, probably during the 6th century, the castle suffered severe damages and it was abandoned.It was revived and repaired in the 10th century, around 915, but soon it was detroyed again. It remained in use as a fortified settlement until the 14th century.The castle covers an area of 15,000 square meters and the length of the remaining walls is around 1000 meters, at a maximum height of 4 to 5 meters.',st_GeomFromText('POINT(40.458481 23.621429)',132));
insert into monument (name,place,region,description,point) values('ANCIENT OLYNTHOS','CHALKIDIKI','CENTRAL MACEDONIA','The area was first settled in the Neolithic Age (5300-4500 BC) and the word “Olynthus” is pre-Hellenic and most possibly means “wild fig”.Tradition has it that it was thus named by Olynthus,one of the sons of the river deity Strymon.Herodotus mentions that the city was colonized by Boetiaeans from Imathia in the seventh century BC. ',st_GeomFromText('POINT(40.296287 23.354414)',132));
insert into monument (name,place,region,description,point) values('ANCIENT SANI','CHALKIDIKI','CENTRAL MACEDONIA','One of the three colonies of Andros in Chalkidiki, was founded in the 7th century BC.On the southwest coast of Akti (Mount Athos peninsula),facing the Gulf of Siggiti.The choice of location is probably related to the existence of the well-known mines within a short distance of it, as well as to the fact that this location offered ships safe access to the south sea,avoiding the dangerous passage of Mount Athos, thus facilitating the trade.',st_GeomFromText('POINT(40.362610 23.932140)',132));
insert into monument (name,place,region,description,point) values('THE PETRALONA CAVE','CHALKIDIKI','CENTRAL MACEDONIA','The Petralona Cave is about one kilometer from the village of Petralona in the prefecture of Halkidiki,Macedonia.It has been open to the public since 1979.The cave was discovered by Aris Poulianos,the traces of habitation of Arhanthropi,about 700,000 years,according to the very oldest European ancestors that have been found so far.',st_GeomFromText('POINT(40.374892 23.167993)',132));
insert into monument (name,place,region,description,point) values('TEMPLES AMMON ZEUS','CHALKIDIKI','CENTRAL MACEDONIA','One of the important temples that have been found in Chalkidiki is Ammon Zeus,which was discovered in 1969 on the occasion of the construction of a hotel,causing partial destruction of the crest of the cult.The excavation that continued in the years 1970,1971 and 1973 showed that in this place the peninsula of Kassandra was founded in the second half of the 8th century BC by the Evoi colonists of the city of Afiti,sanctuary of Dionysus,worshiped together with Nymphs in the cave below the rock on the southwest slope of the area.Worship in the cave,where the faithful reached a scaled scale,continued in the following centuries until the 2nd century AD.',st_GeomFromText('POINT(40.076932 23.448551)',132));
insert into monument (name,place,region,description,point) values('MONUMENT OF ALEXANDER THE GREAT','THESSALONIKI','CENTRAL MACEDONIA','The imposing bronze statue of Alexander the Great riding his faithful companion of 20 years, Bucephalus, dominates Thessalonikis Nea Paralia, a few meters away from another city landmark, the White Tower. This is one of the citys most photographed sights, which was erected in 1973 with public fundraising. It was unveiled in 1974. The equestrian statue of the Macedonian commander was created by the sculptor Evangelos Moustakas and is the tallest in Greece, reaching almost 6.15 meters in height.',st_GeomFromText('POINT(40.624061 22.950005)',132));
insert into monument (name,place,region,description,point) values('STATUE OF ARISTOTLE','THESSALONIKI','CENTRAL MACEDONIA','In the heart of Thessaloniki, just a stone’s throw from the promenade, there is one of the most well-known places in the city — the square of Aristotle. At this place various city events take place, the magnificent twin buildings of Electra Palace and Olympion are situated here, you can feed pigeons right from your hands or enjoy a slow walk at the picturesque streets. Nearby multifarious cafes, lots of shops and boutiques are located, and one of the main sites of interest, sure enough, is the monument to Aristotle.',st_GeomFromText('POINT(40.632239 22.941099)',132));
insert into monument (name,place,region,description,point) values('STATUE OF PHILIP II','THESSALONIKI','CENTRAL MACEDONIA','To the east from the White Tower a large enough green park area can be found. It is bordered by Manoli Andronikou street, Nikolau Germanou street and the promenade itself. Stretching to the south along the bay together with the Leoforos 30is Oktovriou street and Leoforos Meg.Alexandrou street, it turns now and then into different gardens and theme parks, which hide inside themselves a lot of memorials and sculptures. In memorial park, quite near the White Tower, there are monuments to some outstanding Greek persons. Among them one can find a statue of the Macedonian king Philip II — a great ruler, who played an important role in the establishment of powerful state of Ancient Greece.',st_GeomFromText('POINT(40.626145 22.949533)',132));
insert into monument (name,place,region,description,point) values('AGION OROS','AGION OROS','AGION OROS','AGION OROS is a mountain and peninsula in northeastern Greece and an important centre of Eastern Orthodox monasticism. It is governed as an autonomous polity within the Greek Republic. Mount Athos is home to 20 monasteries under the direct jurisdiction of the Ecumenical Patriarch of Constantinople.',st_GeomFromText('POINT(40.264493 24.215273)',132));

--Region of Western Macedonia
insert into monument (name,place,region,description,point) values('NATURAL HISTORY MUSEUM','KOZANI','WESTERN MACEDONIA','The first historical – folklore collection was established at the end of 1968 to the beginning of 1969 and it was housed at times in various rented, small shops around the city. From 1975 to 1984, it was housed in a building of the Charitable Sisterhood of Kozani. In 1979, the Natural History Museum was founded in the aforementioned building. In this first exhibition, the historical department held the whole history of Kozani. At the same time, the folklore collection was composed, in which the following themes were exhibited: traditional occupations of primary production, workshops and trades, spiritual and social life, family life. The collections above were transferred four times to various rented, but unsuitable buildings. The Associations administration was always concerned with the issue of permanent housing for the collections in a building of their own. In the years 1980-1983, the building was constructed, in which the Museum is housed today. In 1993, a new, four-storey building was raised, as an extension to the first one, in order to house the Museums new wing',st_GeomFromText('POINT(40.301251 21.785156)',132));
insert into monument (name,place,region,point) values('AGIOU NIKOLAOU CLOCK TOWER','KOZANI','WESTERN MACEDONIA',st_GeomFromText('POINT(40.3008415 21.7878839)',132));
insert into monument (name,place,region,description,point) values('ANITSAS MONUMENT','GREVENA','WESTERN MACEDONIA','On the hill "Annitsa" that dominates between Samarina and the Philippines, a small Greek military unit staffed mainly by men from neighboring villages, not only repulsed the attack, but forced the Italians to retreat erratically to the Konitsa area. In memory of the event, the modern monument was built at an altitude of 1728',st_GeomFromText('POINT(40.0828623 21.0737076)',132));
insert into monument (name,place,region,description,point) values('ARCHAEOLOGICAL SITE OF THE PREHISTORIC LAKE SETTLEMENT OF DISPILIO','DISPILIO','WESTERN MACEDONIA','Dispilio is an archaeological site containing remains of a Neolithic lakeshore settlement that occupied an artificial island[1] near the modern village of Dispilio on Lake Orestiada in Kastoria municipality, Western Macedonia, Greece.The lake settlement was discovered during the dry winter of 1932, which lowered the lake level and revealed traces of the settlement. A preliminary survey was made in 1935 by Antonios Keramopoulos. Excavations began in 1992, led by George Chourmouziadis, professor of prehistoric archaeology at the Aristotle University of Thessaloniki. The sites paleoenvironment, botany, fishing techniques, tools and ceramics were published informally in the June 2000 issue of Επτάκυκλος, a Greek archaeology magazine and by Hourmouziadis in 2002. A recreation of the lake dwellers settlement has been erected near the site to attract tourists from Greece and abroad.',st_GeomFromText('POINT(40.4697288 21.2715716)',132));
insert into monument (name,place,region,description,point) values('MUSEUM OF THE MACEDONIAN STRUGGLE','KASTORIA','WESTERN MACEDONIA','The Museum of the Macedonian Struggle in Kastoria, Greece is housed in a traditional old mansion that belonged to the teacher and fighter Anastasios Picheon (1836-1913). It was inaugurated on 23 May 2010, a project of the "Friends of the Museum of the Macedonian Struggle” that was founded in 1993 in the Municipality of Kastoria.The Museum outlines the Greek revolutionary movements that came into being in Macedonia when it was under Ottoman rule and lasted until its liberation and unification with Greece in 1913. With rich iconographic material and artefacts, it focuses mainly on the crucial (for Macedonian Hellenism) period around 1878. At that time there were uprisings and insurgencies in Western Macedonia by the local Greeks in an effort to abrogate the Treaty of San Stefano, to overthrow the Turkish rule and be united with free Greece.',st_GeomFromText('POINT(40.516962 21.271909)',132));
insert into monument (name,place,region,description,point) values('THE BYZANTINE MUSEUM OF KASTORIA','KASTORIA','WESTERN MACEDONIA','The Byzantine Museum of Kastoria contains one of the richest collections of Byzantine and post-Byzantine icons in Greece, which is exhibited in a museum space of the Ministry of Culture. The museums collection consists of portable icons from Byzantine and post-Byzantine temples in the city of Kastoria, frescoed hagiographies, detached early Christian mosaics of Diocletian, architectural members from the apocalyptic apocalyptic ecclesiastical sites, to Ottoman rule.',st_GeomFromText('POINT(40.519249 21.268512)',132));
insert into monument (name,place,region,description,point) values('ARCHAEOLOGICAL MUSEUM OF FLORINA','FLORINA','WESTERN MACEDONIA','The museum is housed in a two-storey building that was constructed in 1969 and renovated internally in 1999. It has prehistoric, Hellenistic, Roman, and Byzantine finds from the Florina area.',st_GeomFromText('POINT(40.780936 21.413774)',132));




