--Region of Attica
insert into monument (name,region,description,point) values('PARTHENON','ATTICA','The magnificent temple on the Acropolis of Athens, known as the Parthenon, was built between 447 and 432 BCE in the Age of Pericles, and it was dedicated to the city’s patron deity Athena.The temple was constructed to house the new cult statue of the goddess by Pheidias and to proclaim to the world the success of Athens as leader of the coalition of Greek forces which had defeated the invading Persian armies of Darius and Xerxes.The temple would remain in use for more than a thousand years, and despite the ravages of time, explosions, looting, and pollution damage, it still dominates the modern city of Athens, a magnificent testimony to the glory and renown the city enjoyed throughout antiquity.',st_GeomFromText('POINT(37.9715285 23.7267166)',132));
insert into monument (name,region,description,point) values('ANCIENT EPIDAURUS','ATTICA','Probably the most beautiful and best preserved of its kind, the theater of Epidaurus was built in the 4th century BC by Polykleitos the Younger. Due to its excellent acoustics and condition, the ancient theater is still used today, most notably under the framework of the annual Epidaurus Festival',st_GeomFromText('POINT(37.596078 23.079244)',132));

--Region of Central Macedonia
insert into monument (name,region,description,point) values('APOSTLE PAULS ALTAR','CENTRAL MACEDONIA','After being chased from Thessaloniki the Apostle Paul went to Veria, where he preached the Holy Gospel to jews and Greeks.The spot in Veria where Paul stood and preached, is called the "Apostle Pauls Altar and is now an imposing monument with beautiful mosaics',st_GeomFromText('POINT(40.519362 22.205216)',132));
insert into monument (name,region,description,point) values('MUSEUM OF ROYAL TOMBS OF AIGAI','CENTRAL MACEDONIA','The museum has a dark,imposing atmosphere that surprises most visitors.Some of the most impressive and important exhibits from the Macedonian dominated period of the Greek history are available in the exact location that the original excavations took place. The museum was built in 1993, 16 years after the discovery of the Royal tombs in Aiges.It was built in order to create ideal conditions considering the humidity and temperature needed for the findings to be properly preserved and protected. Inside the museum there are four separate tombs and the “Heroon”, a small temple built for Phillip II of Macedon.',st_GeomFromText('POINT(40.487537 22.320730)',132));
insert into monument (name,region,description,point) values('ROTONDA','CENTRAL MACEDONIA','The famous Rotonda of Thessaloniki, Macedonia: The Rotonda (or Rotunda) is one of the most important Roman monuments in Thessaloniki. It stands just next to the Arch of Galerius in the city center and it is also known as the Church of Agios Georgios. This cylindrical structure was built in 306 AD by the Roman tetrarch Galerius, who intended it to be his grave. At first, it worked as a temple but it remains unknown to which god this temple was dedicated.',st_GeomFromText('POINT(40.633301 22.952854)',132));
insert into monument (name,region,description,point) values('THE GALERIUS PALACE','CENTRAL MACEDONIA','Where Navarinou Square and Demetriou Gounari Street is now located, a significant part of the Galerius Palace complex has been excavated including massive walls, a large internal courtyard, peristyle, corridors and rooms with beautiful mosaic floors, fountains and springs. On the southwest part of the site is where the Octagon lies, a large octagonal stucture of almost 30m in internal diameter, which was a temple or the throne room with a wonderful floor paving remaining. The Hippodrome (400m in length), lies on the east of the Palace, unfortunately underneath the block of flats in the Hippodrome Square. Many of its remaining marbles and stones were later used in various repairs to the western walls.',st_GeomFromText('POINT(40.630353 22.948980)',132));
insert into monument (name,region,description,point) values('THE ROMAN MARKET','CENTRAL MACEDONIA','During the Roman period, this marketplace represented the social and religious center of the town and had the most imposing buildings. The complex of the Roman market was constructed around a rectangular square. In the three sides, there were two lofts. The southern loft was seating at a double vaulting which was a semi-basement on the one side.On the eastern loft of the transept, there was a building display. According to a sign, it functioned as a conservatory. During the Byzantine Period, the buildings were deserted and destroyed by earthquakes or enemy invasions.',st_GeomFromText('POINT(40.630353 22.948980)',132));
--Region of Agion oros
insert into monument (name,region,description,point) values('AGION OROS','AGION OROS','AGION OROS is a mountain and peninsula in northeastern Greece and an important centre of Eastern Orthodox monasticism. It is governed as an autonomous polity within the Greek Republic. Mount Athos is home to 20 monasteries under the direct jurisdiction of the Ecumenical Patriarch of Constantinople.',st_GeomFromText('POINT(40.264493 24.215273)',132)) ;


