//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.16 at 08:10:19 PM EEST 
//


package com.soap.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.soap.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.soap.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InputMuseumResponse }
     * 
     */
    public InputMuseumResponse createInputMuseumResponse() {
        return new InputMuseumResponse();
    }

    /**
     * Create an instance of {@link FindNamesLargerInputValueResponse }
     * 
     */
    public FindNamesLargerInputValueResponse createFindNamesLargerInputValueResponse() {
        return new FindNamesLargerInputValueResponse();
    }

    /**
     * Create an instance of {@link FindNamesLargerInputValueRequest }
     * 
     */
    public FindNamesLargerInputValueRequest createFindNamesLargerInputValueRequest() {
        return new FindNamesLargerInputValueRequest();
    }

    /**
     * Create an instance of {@link FindMuseumRequest }
     * 
     */
    public FindMuseumRequest createFindMuseumRequest() {
        return new FindMuseumRequest();
    }

    /**
     * Create an instance of {@link UpdateMuseumRequest }
     * 
     */
    public UpdateMuseumRequest createUpdateMuseumRequest() {
        return new UpdateMuseumRequest();
    }

    /**
     * Create an instance of {@link DeleteMuseumRequest }
     * 
     */
    public DeleteMuseumRequest createDeleteMuseumRequest() {
        return new DeleteMuseumRequest();
    }

    /**
     * Create an instance of {@link DeleteMuseumResponse }
     * 
     */
    public DeleteMuseumResponse createDeleteMuseumResponse() {
        return new DeleteMuseumResponse();
    }

    /**
     * Create an instance of {@link FindNearestNameRequest }
     * 
     */
    public FindNearestNameRequest createFindNearestNameRequest() {
        return new FindNearestNameRequest();
    }

    /**
     * Create an instance of {@link FindByPlaceMuseumsResponse }
     * 
     */
    public FindByPlaceMuseumsResponse createFindByPlaceMuseumsResponse() {
        return new FindByPlaceMuseumsResponse();
    }

    /**
     * Create an instance of {@link Museum }
     * 
     */
    public Museum createMuseum() {
        return new Museum();
    }

    /**
     * Create an instance of {@link UpdateMuseumResponse }
     * 
     */
    public UpdateMuseumResponse createUpdateMuseumResponse() {
        return new UpdateMuseumResponse();
    }

    /**
     * Create an instance of {@link FindNearestNameResponse }
     * 
     */
    public FindNearestNameResponse createFindNearestNameResponse() {
        return new FindNearestNameResponse();
    }

    /**
     * Create an instance of {@link FindByPlaceMuseumsRequest }
     * 
     */
    public FindByPlaceMuseumsRequest createFindByPlaceMuseumsRequest() {
        return new FindByPlaceMuseumsRequest();
    }

    /**
     * Create an instance of {@link InputMuseumRequest }
     * 
     */
    public InputMuseumRequest createInputMuseumRequest() {
        return new InputMuseumRequest();
    }

    /**
     * Create an instance of {@link FindByRegionMuseumsRequest }
     * 
     */
    public FindByRegionMuseumsRequest createFindByRegionMuseumsRequest() {
        return new FindByRegionMuseumsRequest();
    }

    /**
     * Create an instance of {@link FindByRegionMuseumsResponse }
     * 
     */
    public FindByRegionMuseumsResponse createFindByRegionMuseumsResponse() {
        return new FindByRegionMuseumsResponse();
    }

    /**
     * Create an instance of {@link FindMuseumResponse }
     * 
     */
    public FindMuseumResponse createFindMuseumResponse() {
        return new FindMuseumResponse();
    }

}
