//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.25 at 06:47:38 AM EEST 
//


package com.soap.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.soap.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.soap.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetNearestNameResponse }
     * 
     */
    public GetNearestNameResponse createGetNearestNameResponse() {
        return new GetNearestNameResponse();
    }

    /**
     * Create an instance of {@link GetNamesLargerInputValueResponse }
     * 
     */
    public GetNamesLargerInputValueResponse createGetNamesLargerInputValueResponse() {
        return new GetNamesLargerInputValueResponse();
    }

    /**
     * Create an instance of {@link GetNearestNameRequest }
     * 
     */
    public GetNearestNameRequest createGetNearestNameRequest() {
        return new GetNearestNameRequest();
    }

    /**
     * Create an instance of {@link GetNamesLargerInputValueRequest }
     * 
     */
    public GetNamesLargerInputValueRequest createGetNamesLargerInputValueRequest() {
        return new GetNamesLargerInputValueRequest();
    }

    /**
     * Create an instance of {@link Monument }
     * 
     */
    public Monument createMonument() {
        return new Monument();
    }

}
